### ISSUE TITLE
変調「不運」の挙動について

### ISSUE THREAD

**Issue by keyslock** [ksx0330/FVTT-Magicalogia-System#2]
マギカロギアにおける変調「不運」の挙動が、実際のルールと若干異なる挙動となっています。

## FVTT上の挙動
1. 「不運」となっている特技が使用不能（判定が行えない）

## ルールの挙動
1. 「不運」となっている特技が使用不能（判定が行えない）
2. その分野の特技が指定特技になった判定を行うとき、マイナス1の修正がつく

**Comment by ksx0330** [comment]
Fixed in version 0.1.6
